// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuIyptbFLUG7EiOGfmkfBD04JuJxDMzlM',
    appId: '1:521598994388:web:8aacc8df5aec8ca8f27841',
    messagingSenderId: '521598994388',
    projectId: 'crud-33ba6',
    authDomain: 'crud-33ba6.firebaseapp.com',
    storageBucket: 'crud-33ba6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDx7E66dQzZyTg7NeW2p5vSVZNiltIpQ',
    appId: '1:521598994388:android:108f4bc17bdecfd2f27841',
    messagingSenderId: '521598994388',
    projectId: 'crud-33ba6',
    storageBucket: 'crud-33ba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUb1Pk2HyqKVuYQvwlovyEK7ftMVr9LsE',
    appId: '1:521598994388:ios:d3f0bdf31ee81023f27841',
    messagingSenderId: '521598994388',
    projectId: 'crud-33ba6',
    storageBucket: 'crud-33ba6.appspot.com',
    iosClientId: '521598994388-t9k5obe2khs3apb4pi77r93in2i2lj5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUb1Pk2HyqKVuYQvwlovyEK7ftMVr9LsE',
    appId: '1:521598994388:ios:d3f0bdf31ee81023f27841',
    messagingSenderId: '521598994388',
    projectId: 'crud-33ba6',
    storageBucket: 'crud-33ba6.appspot.com',
    iosClientId: '521598994388-t9k5obe2khs3apb4pi77r93in2i2lj5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
